/* eslint-disable react-refresh/only-export-components -- the provider and its hook intentionally share one public module */
import { createContext, useContext, useEffect, useMemo, useState, type ReactNode } from "react";

export type Locale = "hy" | "ru" | "en";

type LanguageContextValue = {
  locale: Locale;
  setLocale: (locale: Locale) => void;
  t: (key: string) => string;
};

const STORAGE_KEY = "vizit-locale";

const dictionaries: Record<Locale, Record<string, string>> = {
  hy: {
    "nav.home": "Գլխավոր",
    "nav.services": "Ծառայություններ",
    "nav.how": "Ինչպես է աշխատում",
    "nav.businesses": "Գործընկերներ",
    "nav.map": "Քարտեզ",
    "nav.pricing": "Գներ",
    "nav.about": "Մեր մասին",
    "nav.contact": "Կապ",
    "nav.login": "Մուտք",
    "nav.start": "Սկսել անվճար",
    "nav.tagline": "Ամրագրման միջավայր",
    "nav.openMenu": "Բացել մենյուն",
    "hero.badge": "Առցանց ամրագրում՝ մի քանի րոպեում",
    "hero.title1": "Ձեր այցը՝",
    "hero.title2": "առանց հերթի",
    "hero.titlePunctuation": "։",
    "hero.subtitle": "Գտեք մոտակա սրահը, կլինիկան կամ մասնագետին, ընտրեք ազատ ժամը և ամրագրեք առանց զանգերի ու սպասման։",
    "hero.proof.availability": "Ազատ ժամերը՝ իրական ժամանակում",
    "hero.proof.noCalls": "Առանց զանգերի",
    "hero.proof.reminders": "Հիշեցումներ՝ SMS-ով կամ էլ. փոստով",
    "ticket.queue": "Ամրագրման համար",
    "ticket.visit": "Այց",
    "ticket.visitValue": "Ընտրված ծառայություն",
    "ticket.date": "Ամսաթիվ",
    "ticket.dateValue": "Այսօր",
    "ticket.time": "Ժամ",
    "ticket.confirmed": "Հաստատված",
    "ticket.next": "Հաջորդ այցը",
    "search.label": "Ի՞նչ ծառայություն եք փնտրում",
    "search.placeholder": "Օրինակ՝ սրահ, ատամնաբույժ, մերսում",
    "search.location": "Վայրը",
    "search.city": "Երևան",
    "search.cityFixed": "Այս պահին հասանելի է Երևանը",
    "search.useLocation": "Օգտագործել իմ գտնվելու վայրը",
    "search.currentLocation": "Իմ գտնվելու վայրը",
    "search.locating": "Որոշվում է…",
    "search.locationError": "Չհաջողվեց որոշել վայրը։ Ստուգեք դիտարկիչի թույլտվությունը։",
    "search.locationUnsupported": "Այս դիտարկիչը չի աջակցում տեղորոշմանը։",
    "search.button": "Որոնել",
    "popular": "Հանրաճանաչ որոնումներ՝",
    "categories.title": "Բացահայտեք ծառայությունները",
    "categories.all": "Բոլոր կատեգորիաները",
    "categories.empty.title": "Կատեգորիաներ դեռ չկան",
    "categories.empty.text": "Շուտով այստեղ կտեսնես հասանելի կատեգորիաները։",
    "how.badge": "Պարզ գործընթաց",
    "how.title": "Երեք քայլ մինչև ձեր այցը",
    "steps.search.title": "Գտեք ծառայությունը",
    "steps.search.text": "Փնտրեք ըստ ծառայության, մասնագետի, կլինիկայի կամ սրահի անվան։",
    "steps.time.title": "Ընտրեք ազատ ժամը",
    "steps.time.text": "Տեսեք հասանելի ժամերը և ընտրեք ձեզ հարմարը։",
    "steps.confirm.title": "Ստացեք հաստատումը",
    "steps.confirm.text": "Ամրագրումն անմիջապես հաստատվում է, իսկ դուք ստանում եք հիշեցում։",
    "businesses.badge": "Գրանցված բիզնեսներ",
    "businesses.title": "Ընտրիր բիզնեսը և ամրագրիր ազատ ժամը",
    "businesses.text": "Գտիր քեզ հարմար բիզնեսը և ամրագրիր ազատ ժամը։",
    "businesses.all": "Բոլորը",
    "businesses.services": "Ծառայություններ",
    "businesses.healthcare": "Բժշկական",
    "businesses.empty.title": "Բիզնես չի գտնվել",
    "businesses.empty.text": "",
    "business.card.book": "Ամրագրել",
    "business.card.view": "Տեսնել էջը",
    "business.card.noAddress": "Հասցեն նշված չէ",
    "business.card.defaultDescription": "Ծառայություններ, մասնագետներ և օնլայն ամրագրում։",
    "business.card.services": "ծառայություն",
    "business.card.staff": "մասնագետ",
    "category.fallback": "Կատեգորիա",
    "map.badge": "Քարտեզով որոնում",
    "map.title": "Գտիր մոտակայքում գտնվող բիզնեսները",
    "map.selectedAddress": "Ընտրված հասցե",
    "map.bookAddress": "Ամրագրել այս հասցեում",
    "map.choosePin": "Ընտրիր քարտեզի նշիչը",
    "map.choosePinText": "Սեղմիր քարտեզի վրա երևացող բիզնեսը՝ մանրամասները տեսնելու և ամրագրելու համար։",
    "map.instructions": "Քաշիր քարտեզը, մեծացրու կամ փոքրացրու և ընտրիր հասցեն",
    "map.zoomIn": "Մեծացնել քարտեզը",
    "map.zoomOut": "Փոքրացնել քարտեզը",
    "map.center": "Կենտրոնացնել քարտեզը",
    "map.emptyTitle": "Քարտեզի հասցեներ դեռ չկան",
    "map.emptyText": "Քարտեզում ցուցադրվող հասցեներ դեռ չեն ավելացվել։",
    "seo.homeTitle": "Vizit.am — օնլայն ամրագրում ծառայությունների և բժշկական այցերի համար",
    "seo.homeDescription": "Գտիր ծառայություններն ու բժշկական կենտրոնները, տես քարտեզում, ընտրիր բիզնեսը և ամրագրիր ազատ ժամը Vizit.am-ում։",
    "seo.imageAlt": "Vizit օնլայն ամրագրում",
    "stats.businesses": "Գործընկերներ",
    "stats.services": "Ծառայություններ",
    "stats.staff": "Մասնագետներ",
    "stats.categories": "Կատեգորիաներ",
    "plans.badge": "Պլաններ",
    "plans.title": "Ընտրիր հարմար պլանը",
    "plans.text": "",
    "plans.businessPlan": "Պլան բիզնեսի համար",
    "cta.badge": "Բիզնեսների համար",
    "cta.title": "Դարձրու քո բիզնեսը տեսանելի և ամրագրելի",
    "cta.text": "Կառավարիր ամրագրումները, հաճախորդներին, թիմը և վճարումները մեկ հարթակից։",
    "cta.pricing": "Տեսնել պլանները",
    "benefits.fast.title": "Արագ ամրագրում",
    "benefits.fast.text": "Հաճախորդը գտնում է ծառայությունը, տեսնում ազատ ժամերը և ամրագրում առանց զանգերի։",
    "benefits.secure.title": "Հստակ և ապահով",
    "benefits.secure.text": "Բիզնեսի էջը, մասնագետները, ծառայությունները և հասանելի ժամերը մեկ տեղում են։",
    "benefits.real.title": "Միշտ հասանելի",
    "benefits.real.text": "Գտիր ծառայությունները և ամրագրիր քեզ հարմար պահին։",
    "benefits.growth.title": "Բիզնեսների աճ",
    "benefits.growth.text": "Ավելացրու նոր ծառայություններ, վաճառքներ և հաճախորդների վերադարձը։",
    "status.loading": "Բեռնվում է...",
    "status.errorBusinesses": "Բիզնեսների ցուցակը ժամանակավորապես հասանելի չէ։",
    "status.errorPlans": "Չհաջողվեց բեռնել պլանները։",
    "footer.badge": "Vizit բիզնեսների համար",
    "footer.title": "Քո բիզնեսը նույնպես կարող է ունենալ պրոֆեսիոնալ հանրային ամրագրման էջ",
    "footer.text": "Գրանցիր քո սրահը կամ կլինիկան, ստացիր օրացույց, թիմի կառավարում, հանրային ամրագրման հոսք և ավելի վստահելի թվային ներկայություն։",
    "footer.platformTagline": "Ամրագրման հարթակ",
    "footer.description": "Vizit-ը ստեղծված է գեղեցկության, ատամնաբուժական և այլ ծառայությունների բիզնեսների համար՝ ամրագրումները պարզ, արագ ու վստահելի դարձնելու նպատակով։",
    "footer.onlineBooking": "Օնլայն ամրագրումներ",
    "footer.supportAvailable": "Աջակցություն հասանելի է",
    "footer.navigation": "Նավարկում",
    "footer.platform": "Հարթակ",
    "footer.legal": "Իրավական",
    "footer.features": "Ֆունկցիաներ",
    "footer.support": "Աջակցություն",
    "footer.faq": "Հաճախ տրվող հարցեր",
    "footer.register": "Գրանցում",
    "footer.privacy": "Գաղտնիություն",
    "footer.terms": "Պայմաններ",
    "footer.cookies": "Cookie-ներ",
    "footer.rights": "Բոլոր իրավունքները պաշտպանված են։",
    "footer.appointmentBusinesses": "Ժամադրություններով աշխատող բիզնեսների համար։",
  },
  ru: {
    "nav.home": "Главная",
    "nav.services": "Услуги",
    "nav.how": "Как работает",
    "nav.businesses": "Партнёры",
    "nav.map": "Карта",
    "nav.pricing": "Цены",
    "nav.about": "О нас",
    "nav.contact": "Контакты",
    "nav.login": "Войти",
    "nav.start": "Начать бесплатно",
    "nav.tagline": "Платформа бронирования",
    "nav.openMenu": "Открыть меню",
    "hero.badge": "Онлайн-запись за несколько минут",
    "hero.title1": "Ваш визит —",
    "hero.title2": "без очереди",
    "hero.titlePunctuation": ".",
    "hero.subtitle": "Найдите ближайший салон, клинику или специалиста, выберите свободное время и запишитесь без звонков и ожидания.",
    "hero.proof.availability": "Свободное время в реальном времени",
    "hero.proof.noCalls": "Без звонков",
    "hero.proof.reminders": "Напоминания по SMS или эл. почте",
    "ticket.queue": "Номер записи",
    "ticket.visit": "Визит",
    "ticket.visitValue": "Выбранная услуга",
    "ticket.date": "Дата",
    "ticket.dateValue": "Сегодня",
    "ticket.time": "Время",
    "ticket.confirmed": "Подтверждено",
    "ticket.next": "Следующий визит",
    "search.label": "Какую услугу ищете?",
    "search.placeholder": "Например: салон, стоматолог, массаж",
    "search.location": "Место",
    "search.city": "Ереван",
    "search.cityFixed": "Сейчас доступен Ереван",
    "search.useLocation": "Использовать моё местоположение",
    "search.currentLocation": "Моё местоположение",
    "search.locating": "Определяем…",
    "search.locationError": "Не удалось определить местоположение. Проверьте разрешение браузера.",
    "search.locationUnsupported": "Этот браузер не поддерживает геолокацию.",
    "search.button": "Найти",
    "popular": "Популярные запросы:",
    "categories.title": "Выберите категорию",
    "categories.all": "Все категории",
    "categories.empty.title": "Категорий пока нет",
    "categories.empty.text": "Скоро здесь появятся доступные категории.",
    "how.badge": "Простой процесс",
    "how.title": "Три шага до вашего визита",
    "steps.search.title": "Найдите услугу",
    "steps.search.text": "Ищите по услуге, специалисту, клинике или названию салона.",
    "steps.time.title": "Выберите свободное время",
    "steps.time.text": "Посмотрите доступное время и выберите удобный вариант.",
    "steps.confirm.title": "Получите подтверждение",
    "steps.confirm.text": "Запись подтверждается сразу, а вы получаете напоминание.",
    "businesses.badge": "Зарегистрированные бизнесы",
    "businesses.title": "Выберите бизнес и забронируйте время",
    "businesses.text": "Найдите подходящий бизнес и забронируйте свободное время.",
    "businesses.all": "Все",
    "businesses.services": "Услуги",
    "businesses.healthcare": "Медицина",
    "businesses.empty.title": "Бизнес не найден",
    "businesses.empty.text": "",
    "business.card.book": "Забронировать",
    "business.card.view": "Открыть",
    "business.card.noAddress": "Адрес не указан",
    "business.card.defaultDescription": "Услуги, специалисты и онлайн-бронирование.",
    "business.card.services": "услуг",
    "business.card.staff": "специалистов",
    "category.fallback": "Категория",
    "map.badge": "Поиск на карте",
    "map.title": "Найдите бизнесы поблизости",
    "map.selectedAddress": "Выбранный адрес",
    "map.bookAddress": "Забронировать по этому адресу",
    "map.choosePin": "Выберите точку на карте",
    "map.choosePinText": "Нажмите на бизнес на карте, чтобы посмотреть детали и забронировать.",
    "map.instructions": "Перемещайте и масштабируйте карту, затем выберите адрес",
    "map.zoomIn": "Увеличить карту",
    "map.zoomOut": "Уменьшить карту",
    "map.center": "Центрировать карту",
    "map.emptyTitle": "Адресов на карте пока нет",
    "map.emptyText": "Адреса для отображения на карте ещё не добавлены.",
    "seo.homeTitle": "Vizit.am — онлайн-бронирование услуг и медицинских визитов",
    "seo.homeDescription": "Находите услуги и медицинские центры, смотрите их на карте, выбирайте бизнес и бронируйте свободное время на Vizit.am.",
    "seo.imageAlt": "Онлайн-бронирование Vizit",
    "stats.businesses": "Партнёры",
    "stats.services": "Услуги",
    "stats.staff": "Специалисты",
    "stats.categories": "Категории",
    "plans.badge": "Планы",
    "plans.title": "Выберите подходящий тариф",
    "plans.text": "",
    "plans.businessPlan": "Тариф для бизнеса",
    "cta.badge": "Для бизнеса",
    "cta.title": "Сделайте бизнес видимым и доступным для бронирования",
    "cta.text": "Управляйте записями, клиентами, командой и платежами в одном месте.",
    "cta.pricing": "Посмотреть тарифы",
    "benefits.fast.title": "Быстрое бронирование",
    "benefits.fast.text": "Клиент находит услугу, видит свободное время и бронирует без звонков.",
    "benefits.secure.title": "Понятно и надёжно",
    "benefits.secure.text": "Публичная страница бизнеса, специалисты, услуги и доступное время собраны в одном месте.",
    "benefits.real.title": "Всегда доступно",
    "benefits.real.text": "Находите услуги и бронируйте удобное время.",
    "benefits.growth.title": "Рост бизнеса",
    "benefits.growth.text": "Развивайте услуги, продажи и возвращаемость клиентов.",
    "status.loading": "Загрузка...",
    "status.errorBusinesses": "Список бизнесов временно недоступен.",
    "status.errorPlans": "Не удалось загрузить планы.",
    "footer.badge": "Vizit для бизнеса",
    "footer.title": "У вашего бизнеса тоже может быть профессиональная страница онлайн-бронирования",
    "footer.text": "Зарегистрируйте салон или клинику и получите календарь, управление командой, публичное бронирование и более сильное цифровое присутствие.",
    "footer.platformTagline": "Платформа бронирования",
    "footer.description": "Vizit создан для компаний в сфере красоты, стоматологии и услуг, чтобы сделать бронирование проще, быстрее и надёжнее.",
    "footer.onlineBooking": "Онлайн-бронирование",
    "footer.supportAvailable": "Поддержка доступна",
    "footer.navigation": "Навигация",
    "footer.platform": "Платформа",
    "footer.legal": "Правовая информация",
    "footer.features": "Возможности",
    "footer.support": "Поддержка",
    "footer.faq": "Частые вопросы",
    "footer.register": "Регистрация",
    "footer.privacy": "Конфиденциальность",
    "footer.terms": "Условия",
    "footer.cookies": "Cookie",
    "footer.rights": "Все права защищены.",
    "footer.appointmentBusinesses": "Для бизнеса, работающего по записи.",
  },
  en: {
    "nav.home": "Home",
    "nav.services": "Services",
    "nav.how": "How it works",
    "nav.businesses": "Partners",
    "nav.map": "Map",
    "nav.pricing": "Pricing",
    "nav.about": "About",
    "nav.contact": "Contact",
    "nav.login": "Login",
    "nav.start": "Start free",
    "nav.tagline": "Booking platform",
    "nav.openMenu": "Open menu",
    "hero.badge": "Book online in a few minutes",
    "hero.title1": "Your visit,",
    "hero.title2": "without the queue",
    "hero.titlePunctuation": ".",
    "hero.subtitle": "Find a nearby salon, clinic or specialist, choose an available time and book without calls or waiting.",
    "hero.proof.availability": "Live availability",
    "hero.proof.noCalls": "No phone calls",
    "hero.proof.reminders": "SMS or email reminders",
    "ticket.queue": "Booking number",
    "ticket.visit": "Visit",
    "ticket.visitValue": "Selected service",
    "ticket.date": "Date",
    "ticket.dateValue": "Today",
    "ticket.time": "Time",
    "ticket.confirmed": "Confirmed",
    "ticket.next": "Next visit",
    "search.label": "What service are you looking for?",
    "search.placeholder": "For example: salon, dentist, massage",
    "search.location": "Location",
    "search.city": "Yerevan",
    "search.cityFixed": "Yerevan is currently available",
    "search.useLocation": "Use my current location",
    "search.currentLocation": "My current location",
    "search.locating": "Locating…",
    "search.locationError": "Could not determine your location. Check the browser permission.",
    "search.locationUnsupported": "This browser does not support geolocation.",
    "search.button": "Search",
    "popular": "Popular searches:",
    "categories.title": "Explore services",
    "categories.all": "All categories",
    "categories.empty.title": "No categories yet",
    "categories.empty.text": "Available categories will appear here soon.",
    "how.badge": "Simple process",
    "how.title": "Three steps to your visit",
    "steps.search.title": "Find a service",
    "steps.search.text": "Search by service, specialist, clinic or salon name.",
    "steps.time.title": "Choose an available time",
    "steps.time.text": "See live availability and pick the time that suits you.",
    "steps.confirm.title": "Get confirmation",
    "steps.confirm.text": "Your booking is confirmed right away and a reminder is sent to you.",
    "businesses.badge": "Registered businesses",
    "businesses.title": "Choose a business and book a time",
    "businesses.text": "Find the right business and book an available time.",
    "businesses.all": "All",
    "businesses.services": "Services",
    "businesses.healthcare": "Healthcare",
    "businesses.empty.title": "No businesses found",
    "businesses.empty.text": "",
    "business.card.book": "Book",
    "business.card.view": "View page",
    "business.card.noAddress": "Address not provided",
    "business.card.defaultDescription": "Services, specialists and online booking.",
    "business.card.services": "services",
    "business.card.staff": "specialists",
    "category.fallback": "Category",
    "map.badge": "Map search",
    "map.title": "Find businesses near you",
    "map.selectedAddress": "Selected address",
    "map.bookAddress": "Book at this address",
    "map.choosePin": "Choose a map pin",
    "map.choosePinText": "Select a business on the map to view details and book.",
    "map.instructions": "Drag or zoom the map, then choose an address",
    "map.zoomIn": "Zoom in",
    "map.zoomOut": "Zoom out",
    "map.center": "Center map",
    "map.emptyTitle": "No mapped addresses yet",
    "map.emptyText": "No addresses have been added to the map yet.",
    "seo.homeTitle": "Vizit.am — online booking for services and medical visits",
    "seo.homeDescription": "Find services and medical centers, view them on the map, choose a business and book an available time on Vizit.am.",
    "seo.imageAlt": "Vizit online booking",
    "stats.businesses": "Partners",
    "stats.services": "Services",
    "stats.staff": "Specialists",
    "stats.categories": "Categories",
    "plans.badge": "Plans",
    "plans.title": "Choose the right plan",
    "plans.text": "",
    "plans.businessPlan": "Business plan",
    "cta.badge": "For businesses",
    "cta.title": "Make your business visible and bookable",
    "cta.text": "Manage bookings, customers, your team and payments from one platform.",
    "cta.pricing": "View pricing",
    "benefits.fast.title": "Fast booking",
    "benefits.fast.text": "Customers find a service, see available times and book without calls.",
    "benefits.secure.title": "Clear and reliable",
    "benefits.secure.text": "Business details, specialists, services and available times in one place.",
    "benefits.real.title": "Always available",
    "benefits.real.text": "Find services and book at a convenient time.",
    "benefits.growth.title": "Business growth",
    "benefits.growth.text": "Grow your services, sales and customer loyalty.",
    "status.loading": "Loading...",
    "status.errorBusinesses": "The business list is temporarily unavailable.",
    "status.errorPlans": "Could not load plans.",
    "footer.badge": "Vizit for businesses",
    "footer.title": "Your business can have a professional public booking page too",
    "footer.text": "Register your salon or clinic and get a calendar, team management, public booking flow and a stronger digital presence.",
    "footer.platformTagline": "Booking platform",
    "footer.description": "Vizit is built for beauty, dental and service businesses to make bookings simpler, faster and more reliable.",
    "footer.onlineBooking": "Online booking",
    "footer.supportAvailable": "Support available",
    "footer.navigation": "Navigation",
    "footer.platform": "Platform",
    "footer.legal": "Legal",
    "footer.features": "Features",
    "footer.support": "Support",
    "footer.faq": "FAQ",
    "footer.register": "Register",
    "footer.privacy": "Privacy",
    "footer.terms": "Terms",
    "footer.cookies": "Cookies",
    "footer.rights": "All rights reserved.",
    "footer.appointmentBusinesses": "For appointment-based businesses.",
  },
};

function readInitialLocale(): Locale {
  if (typeof window === "undefined") return "hy";
  const stored = window.localStorage.getItem(STORAGE_KEY);
  return stored === "hy" || stored === "ru" || stored === "en" ? stored : "hy";
}

const LanguageContext = createContext<LanguageContextValue | null>(null);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [locale, setLocaleState] = useState<Locale>(() => readInitialLocale());

  useEffect(() => {
    document.documentElement.lang = locale;
    window.localStorage.setItem(STORAGE_KEY, locale);
  }, [locale]);

  const value = useMemo<LanguageContextValue>(() => ({
    locale,
    setLocale: setLocaleState,
    t: (key: string) => dictionaries[locale][key] ?? dictionaries.hy[key] ?? key,
  }), [locale]);

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

export function useLanguage() {
  const value = useContext(LanguageContext);
  if (!value) throw new Error("useLanguage must be used inside LanguageProvider");
  return value;
}
