import LegalPageTemplate from "../components/marketing/LegalPageTemplate";
import { LEGAL_DOCUMENT_VERSION, LEGAL_ENTITY, legalOperatorSummary } from "../config/legal";
import { useLanguage } from "../contexts/LanguageContext";

const copy = {
  hy: {
    title: "Գաղտնիության քաղաքականություն",
    description: "Ինչ տվյալներ է մշակում Vizit.am-ը, ինչ նպատակով, ում կարող է փոխանցել և ինչպես կարող եք իրացնել ձեր իրավունքները։",
    operatorTitle: "1. Տվյալների մշակման պատասխանատուն",
    operatorExtra: `Vizit-ի սեփական հաշիվների, աջակցության, անվտանգության, SaaS վճարումների և հանրային հարթակի աշխատանքի համար տվյալների մշակման պատասխանատուն նշված օպերատորն է։ Գաղտնիության դիմումների հասցեն՝ ${LEGAL_ENTITY.email}։`,
    sections: [
      { title: "2. Vizit-ի և բիզնեսի դերերը", items: ["Vizit-ը ինքնուրույն որոշում է բիզնես և հաճախորդի հաշիվների, գրանցման համաձայնության, անվտանգության, աջակցության, տեխնիկական մատյանների և Vizit-ի SaaS վճարումների մշակման նպատակներն ու միջոցները։", "Յուրաքանչյուր բիզնես ինքնուրույն պատասխանատու է իր հաճախորդների ծառայության, այցի, բժշկական կամ այլ մասնագիտական տվյալների օրինական հավաքման և օգտագործման համար։", "Այդ տվյալների մասով Vizit-ը հիմնականում գործում է որպես բիզնեսի հանձնարարությամբ տեխնիկական մշակող՝ օրացույցը, ամրագրումը և հաճախորդների կառավարումը ապահովելու համար։", "Հաճախորդը ծառայության տվյալների վերաբերյալ նախ կարող է դիմել համապատասխան բիզնեսին, իսկ Vizit-ը կաջակցի տեխնիկական պահանջների կատարմանը։"] },
      { title: "3. Մշակվող տվյալների տեսակները", items: ["Հաշվի տվյալներ՝ անուն, էլ. փոստ, հեռախոս, գաղտնաբառի պաշտպանված ներկայացում, դեր, հաստատման և իրավական համաձայնության ամսաթիվ/տարբերակ։", "Բիզնեսի տվյալներ՝ անվանում, կատեգորիա, հասցե, քարտեզի կոորդինատներ, կոնտակտներ, ծառայություններ, գներ, աշխատակիցներ, սենյակներ և աշխատանքային ժամեր։", "Ամրագրման տվյալներ՝ ծառայություն, մասնագետ, վայր, ամսաթիվ/ժամ, կարգավիճակ, հաճախորդի կոնտակտներ և անհրաժեշտ նշումներ։", "SaaS պլանի և հաշվարկի տվյալներ՝ ընտրված պլան, շրջան, սահմանաչափեր, հաշիվներ և գործարքի կարգավիճակ։ Քարտի ամբողջական տվյալները Vizit-ում չեն պահվում։", "Տեխնիկական և անվտանգության տվյալներ՝ IP հասցե, user-agent, սարքի նույնականացուցիչ, մուտքի և գործողությունների մատյաններ, սխալների տվյալներ։", "Հաղորդակցություն՝ աջակցության դիմումներ, կոնտակտային ձևի հաղորդագրություններ և ընտրված ծանուցումների առաքման կարգավիճակ։"] },
      { title: "4. Բժշկական և այլ զգայուն տվյալներ", items: ["Բժշկական ուղղության ամրագրումը կամ բիզնեսի նշումները կարող են բացահայտել առողջությանը վերաբերող տվյալներ։ Դրանք պետք է լրացվեն միայն անհրաժեշտ ծավալով և օրինական հիմքով։", "Բժշկական բիզնեսը պատասխանատու է տեղեկացված համաձայնության, մասնագիտական գաղտնիքի, աշխատակիցների հասանելիությունների և պահպանման կանոնների համար։", "Մի գրեք հանրային կամ ոչ նախատեսված դաշտերում ախտորոշումներ, փաստաթղթեր կամ այլ զգայուն տվյալներ։", "Անչափահասի տվյալները տրամադրում է ծնողը, խնամակալը կամ օրենքով իրավասու անձը։"] },
      { title: "5. Տվյալների աղբյուրները", items: ["Անմիջապես ձեզանից՝ գրանցման, ամրագրման, հաշվի կարգավորման կամ աջակցության ժամանակ։", "Բիզնեսից, երբ այն ստեղծում կամ կառավարում է հաճախորդի ամրագրումը և այցի պատմությունը։", "Google-ից կամ Facebook-ից միայն այն դեպքում, երբ ինքներդ ընտրում եք սոցիալական մուտքը, և միայն նրանց տրամադրած նույնականացման տվյալները։", "Ձեր բրաուզերից կամ սարքից՝ անվտանգության, session-ի և համակարգի աշխատանքի համար։"] },
      { title: "6. Մշակման նպատակներն ու հիմքերը", items: ["Ձեր համաձայնություն և ձեր խնդրանքով պայմանագրի կատարում՝ հաշիվ, ամրագրում, օրացույց, բիզնես գործիքներ, փորձաշրջան և ընտրված պլան տրամադրելու համար։ Օրենքով պայմանագրով ստացված և միայն դրա կատարման համար օգտագործվող տվյալների նկատմամբ համաձայնությունը կարող է համարվել տրված։", "Օրենքով ուղղակի նախատեսված հիմք՝ հաշվապահական, հարկային, պարտադիր իրավական հարցումների և պահպանման համար։", "Անվտանգության, խարդախության կանխարգելման, սխալների հայտնաբերման և ծառայության պաշտպանության տվյալները մշակվում են միայն պայմանագրի կատարման կամ օրենքով սահմանված անվտանգության պարտականության համար անհրաժեշտ նվազագույն ծավալով։", "Առանձին կամավոր համաձայնություն՝ մարքեթինգային հաղորդագրությունների, սոցիալական մուտքի կամ այլ ոչ պարտադիր մշակման համար։ Դրանք պարտադիր չեն հիմնական ծառայությունից օգտվելու համար։", "Համաձայնությունը գործում է նշված նպատակի և պահպանման ժամկետի ընթացքում կամ մինչև հետկանչը։ Հետկանչը դադարեցնում է կամավոր ապագա մշակումը, սակայն չի վերացնում մինչ այդ օրինական մշակումը կամ օրենքով պարտադիր պահպանումը։ Անհրաժեշտ տվյալների համաձայնության հետկանչը կարող է անհնար դարձնել հաշվի կամ ամրագրման սպասարկումը։"] },
      { title: "7. Ում կարող են փոխանցվել տվյալները", items: ["Հոսթինգի, պահուստավորման, էլ. փոստի և տեխնիկական ենթակառուցվածքի մատակարարներին՝ նվազագույն անհրաժեշտ ծավալով։", "Telegram-ին՝ միայն երբ բիզնեսը միացնում է համապատասխան ծանուցումը, և քարտեզի մատակարարին՝ քարտեզը բեռնելիս։", "Google-ին կամ Facebook-ին՝ միայն սոցիալական մուտքն ընտրելիս։", "Բանկին կամ վճարային մատակարարին՝ միայն Vizit-ի SaaS վճարման կամ տվյալ բիզնեսի սեփական ուղիղ վճարային կապի գործարկման դեպքում։ Հաճախորդի ծառայության գումարը փոխանցվում է անմիջապես բիզնեսին։", "Պետական մարմիններին կամ այլ անձանց՝ միայն իրավական պարտադիր պահանջի, իրավունքների պաշտպանության կամ անվտանգության անհրաժեշտության դեպքում։", "Մենք անձնական տվյալներ չենք վաճառում։"] },
      { title: "8. Միջազգային փոխանցումներ", paragraphs: ["Որոշ տեխնիկական մատակարարներ կարող են տվյալներ մշակել Հայաստանի Հանրապետությունից դուրս։ Նման փոխանցումը սահմանափակվում է անհրաժեշտ տվյալներով և կատարվում է կիրառելի իրավական հիմքով, պայմանագրային ու տեխնիկական պաշտպանություններով։ Կոնկրետ օգտագործվող մատակարարների մասին կարող եք հարցում ուղարկել գաղտնիության հասցեին։"] },
      { title: "9. Պահպանում", items: ["Հաշվի և աշխատանքային տվյալները պահվում են հաշվի/բիզնեսի ակտիվության ընթացքում և դրանից հետո այնքան, որքան անհրաժեշտ է փակման, վեճերի, անվտանգության և օրինական պարտավորությունների համար։", "Հաշվապահական ու գործարքային գրառումները պահվում են օրենքով պահանջվող ժամկետով։", "Ամրագրման և մասնագիտական տվյալների պահպանման ժամկետը հիմնականում որոշում է համապատասխան բիզնեսը՝ իր ոլորտային պարտավորություններով։", "Փակման կամ ջնջման օրինական դիմումից հետո տվյալները ջնջվում կամ ապանձնավորվում են, երբ այլևս պահպանման հիմք չկա։ Պահուստային պատճենները վերանում են դրանց անվտանգ հերթափոխի ընթացքում։"] },
      { title: "10. Անվտանգություն", items: ["Կիրառվում են HTTPS, հասանելիության դերեր, գաղտնաբառերի hashing, հարցումների պաշտպանություն, սահմանափակումներ և անվտանգության մատյաններ։", "Աշխատակիցների և բիզնեսների հասանելիությունը պետք է սահմանափակվի ըստ աշխատանքի անհրաժեշտության։", "Որևէ համակարգ չի կարող երաշխավորել բացարձակ անվտանգություն։ Կասկածելի մուտքի կամ հնարավոր խախտման դեպքում անմիջապես գրեք աջակցությանը։", "Օրենքով պահանջվող տվյալների խախտման դեպքում կկատարվեն անհրաժեշտ ուսումնասիրությունն ու ծանուցումները։"] },
      { title: "11. Ձեր իրավունքները", items: ["Ստանալ տեղեկություն մշակման մասին և հասանելիություն ձեր տվյալներին։", "Ուղղել ոչ ճշգրիտ կամ թերի տվյալները։", "Պահանջել արգելափակել կամ ոչնչացնել տվյալները, երբ մշակման օրինական հիմքը բացակայում է, նպատակը կատարված է կամ տվյալները հնացած/անօրինական են՝ հաշվի առնելով պարտադիր պահպանման բացառությունները։", "Հետ վերցնել համաձայնությունը՝ առանց մինչ այդ կատարված օրինական մշակումը անվավեր դարձնելու։", "Բողոքարկել տվյալներ մշակողի գործողությունը կամ անգործությունը և պահանջել օրենքով նախատեսված պաշտպանություն։", "Բողոք ներկայացնել ՀՀ անձնական տվյալների պաշտպանության լիազոր մարմնին կամ դատարան։"] },
      { title: "12. Ինչպես ներկայացնել դիմում", paragraphs: [`Գրեք ${LEGAL_ENTITY.email} հասցեին՝ նշելով հաշվի email-ը կամ հեռախոսը և պահանջի բովանդակությունը։ Անվտանգության համար կարող ենք խնդրել ինքնության ողջամիտ հաստատում։ Դիմումը կքննարկվի օրենքով սահմանված ժամկետում։ Եթե տվյալը վերահսկում է բիզնեսը, հարցումը կուղղվի համապատասխան բիզնեսին կամ կկատարվի նրա օրինական հանձնարարությամբ։`] },
      { title: "13. Մարքեթինգ, cookie-ներ և ավտոմատ որոշումներ", items: ["Մարքեթինգային հաղորդագրությունից կարող եք հրաժարվել հաղորդագրության հղումով կամ աջակցությանը գրելով։ Ծառայողական և անվտանգության հաղորդագրությունները կարող են շարունակվել։", "Cookie-ների և browser storage-ի օգտագործումը բացատրված է Cookie-ների քաղաքականությունում։", "Vizit-ը ներկայում չի ընդունում մարդկանց վրա իրավական կամ համարժեք էական ազդեցություն ունեցող բացառապես ավտոմատ որոշումներ։ Խարդախության կամ trial-ի չարաշահման ավտոմատ ազդանշանը կարող է բերել լրացուցիչ ստուգման։"] },
      { title: "14. Փոփոխություններ և կապ", paragraphs: [`Էական փոփոխության դեպքում այս էջում կհրապարակվի նոր տարբերակ և, անհրաժեշտության դեպքում, կպահանջվի նոր համաձայնություն։ Գաղտնիության հարցեր՝ ${LEGAL_ENTITY.email}, ${LEGAL_ENTITY.phone}։`] },
    ],
  },
  ru: {
    title: "Политика конфиденциальности",
    description: "Какие данные обрабатывает Vizit.am, зачем, кому они могут передаваться и как реализовать свои права.",
    operatorTitle: "1. Ответственный за обработку",
    operatorExtra: `Указанный оператор отвечает за данные аккаунтов Vizit, поддержку, безопасность, SaaS-платежи и работу публичной платформы. Адрес для обращений по данным: ${LEGAL_ENTITY.email}.`,
    sections: [
      { title: "2. Роли Vizit и бизнеса", items: ["Vizit самостоятельно определяет цели и средства обработки данных бизнес- и клиентских аккаунтов, согласий, безопасности, поддержки, технических журналов и SaaS-платежей Vizit.", "Каждый бизнес самостоятельно отвечает за законный сбор и использование сервисных, медицинских и иных профессиональных данных своих клиентов.", "Для этих данных Vizit в основном выступает техническим обработчиком по поручению бизнеса, обеспечивая календарь, запись и управление клиентами.", "По вопросам данных основной услуги клиент может сначала обратиться к бизнесу, а Vizit окажет необходимую техническую поддержку."] },
      { title: "3. Категории данных", items: ["Аккаунт: имя, email, телефон, защищённое представление пароля, роль, дата/версия подтверждения и юридического согласия.", "Бизнес: название, категория, адрес, координаты, контакты, услуги, цены, сотрудники, помещения и рабочие часы.", "Запись: услуга, специалист, место, дата/время, статус, контакты клиента и необходимые заметки.", "SaaS-тариф и расчёты: тариф, период, лимиты, счета и статус операции. Полные данные карты Vizit не хранит.", "Технические данные и безопасность: IP-адрес, user-agent, идентификатор устройства, журналы входа/действий и ошибки.", "Коммуникации: обращения в поддержку, сообщения контактной формы и статус доставки выбранных уведомлений."] },
      { title: "4. Медицинские и иные чувствительные данные", items: ["Медицинская запись или заметки бизнеса могут раскрывать данные о здоровье. Их следует вводить только в необходимом объёме и при наличии законного основания.", "Медицинский бизнес отвечает за информированное согласие, профессиональную тайну, права доступа сотрудников и сроки хранения.", "Не размещайте диагнозы, документы или иные чувствительные данные в публичных либо не предназначенных для этого полях.", "Данные несовершеннолетнего предоставляет родитель, опекун или иное уполномоченное законом лицо."] },
      { title: "5. Источники данных", items: ["Непосредственно от вас при регистрации, записи, настройке аккаунта или обращении в поддержку.", "От бизнеса, когда он создаёт или ведёт запись и историю визитов клиента.", "От Google или Facebook только при выбранном вами социальном входе и только в объёме предоставленных идентификационных данных.", "От браузера или устройства для безопасности, сессии и работы системы."] },
      { title: "6. Цели и основания обработки", items: ["Ваше согласие и исполнение договора по вашему запросу: аккаунт, запись, календарь, бизнес-инструменты, пробный период и выбранный тариф. В предусмотренных законом случаях согласие на данные, полученные по договору и используемые только для его исполнения, может считаться предоставленным.", "Основание, прямо предусмотренное законом: бухгалтерский и налоговый учёт, обязательные юридические запросы и хранение.", "Данные для безопасности, предотвращения мошенничества, диагностики ошибок и защиты сервиса обрабатываются в минимальном объёме, необходимом для исполнения договора или установленной законом обязанности по безопасности.", "Отдельное добровольное согласие: маркетинговые сообщения, социальный вход и иная необязательная обработка. Они не являются условием основной услуги.", "Согласие действует в течение указанной цели и срока хранения либо до отзыва. Отзыв прекращает будущую добровольную обработку, но не отменяет ранее законную обработку и обязательное хранение. Отзыв согласия на необходимые данные может сделать обслуживание аккаунта или записи невозможным."] },
      { title: "7. Получатели данных", items: ["Поставщики хостинга, резервного копирования, email и технической инфраструктуры — в минимально необходимом объёме.", "Telegram — только после подключения бизнесом уведомлений; поставщик карты — при загрузке карты.", "Google или Facebook — только при выборе социального входа.", "Банк или платёжный провайдер — только при SaaS-платеже Vizit либо собственной прямой интеграции бизнеса. Платёж клиента за услугу поступает прямо бизнесу.", "Государственные органы или иные лица — только по обязательному требованию закона, для защиты прав или безопасности.", "Мы не продаём персональные данные."] },
      { title: "8. Международная передача", paragraphs: ["Некоторые технические поставщики могут обрабатывать данные за пределами Республики Армения. Передача ограничивается необходимыми данными и выполняется на применимом правовом основании с договорными и техническими мерами защиты. Список актуальных поставщиков можно запросить по адресу конфиденциальности."] },
      { title: "9. Хранение", items: ["Данные аккаунта и работы хранятся во время активности аккаунта/бизнеса и после неё столько, сколько нужно для закрытия, споров, безопасности и правовых обязанностей.", "Бухгалтерские и транзакционные записи хранятся установленный законом срок.", "Срок хранения данных записи и профессиональных данных в основном определяет соответствующий бизнес с учётом своих отраслевых обязанностей.", "После законного запроса на закрытие или удаление данные удаляются либо обезличиваются, когда основание хранения прекращается. Резервные копии удаляются в ходе их защищённой ротации."] },
      { title: "10. Безопасность", items: ["Используются HTTPS, ролевой доступ, hashing паролей, защита запросов, ограничения и журналы безопасности.", "Доступ сотрудников и бизнеса должен ограничиваться рабочей необходимостью.", "Ни одна система не гарантирует абсолютную безопасность. При подозрительном входе или возможном нарушении сразу обратитесь в поддержку.", "При нарушении данных выполняются расследование и уведомления, требуемые законом."] },
      { title: "11. Ваши права", items: ["Получить информацию об обработке и доступ к своим данным.", "Исправить неточные или неполные данные.", "Потребовать блокирование или уничтожение данных, если нет законного основания, цель достигнута либо данные устарели или обрабатываются незаконно, с учётом обязательного хранения.", "Отозвать согласие без отмены законности обработки до отзыва.", "Обжаловать действие или бездействие обработчика и потребовать предусмотренную законом защиту.", "Подать жалобу в уполномоченный орган Республики Армения по защите персональных данных или в суд."] },
      { title: "12. Как направить запрос", paragraphs: [`Напишите на ${LEGAL_ENTITY.email}, указав email/телефон аккаунта и содержание запроса. Для безопасности мы можем разумно проверить личность. Ответ будет предоставлен в установленный законом срок. Если данные контролирует бизнес, запрос будет направлен ему или выполнен по его законному поручению.`] },
      { title: "13. Маркетинг, cookie и автоматические решения", items: ["От маркетинговых сообщений можно отказаться по ссылке в сообщении или через поддержку. Сервисные и безопасностные сообщения могут продолжаться.", "Cookie и browser storage описаны в Политике cookie.", "Vizit сейчас не принимает исключительно автоматические решения, создающие юридические или сопоставимые существенные последствия. Автоматический сигнал о мошенничестве или злоупотреблении trial может привести к дополнительной проверке."] },
      { title: "14. Изменения и контакты", paragraphs: [`При существенном изменении будет опубликована новая версия и, когда требуется, запрошено новое согласие. Вопросы о данных: ${LEGAL_ENTITY.email}, ${LEGAL_ENTITY.phone}.`] },
    ],
  },
  en: {
    title: "Privacy policy",
    description: "What data Vizit.am processes, why, who may receive it and how you can exercise your rights.",
    operatorTitle: "1. Data controller",
    operatorExtra: `The identified operator controls data used for Vizit accounts, support, security, SaaS payments and the public platform. Privacy requests: ${LEGAL_ENTITY.email}.`,
    sections: [
      { title: "2. Vizit and business roles", items: ["Vizit determines the purposes and means for business/client accounts, consent records, security, support, technical logs and Vizit's SaaS billing.", "Each business is independently responsible for the lawful collection and use of its customers' service, medical and other professional data.", "For that data, Vizit mainly acts as the business's technical processor to provide calendars, bookings and client management.", "A customer may first contact the relevant business about underlying-service data, and Vizit will provide the necessary technical assistance."] },
      { title: "3. Data categories", items: ["Account data: name, email, phone, protected password representation, role, verification and legal-consent date/version.", "Business data: name, category, address, map coordinates, contacts, services, prices, staff, rooms and working hours.", "Booking data: service, specialist, location, date/time, status, customer contacts and necessary notes.", "SaaS plan and billing data: selected plan, period, limits, invoices and transaction status. Vizit does not store full card details.", "Technical and security data: IP address, user-agent, device identifier, login/activity logs and error information.", "Communications: support requests, contact-form messages and delivery status for selected notifications."] },
      { title: "4. Health and other sensitive data", items: ["A healthcare booking or business note may reveal health information. It should be entered only where necessary and on a lawful basis.", "A healthcare business is responsible for informed consent, professional confidentiality, staff access and retention rules.", "Do not place diagnoses, documents or other sensitive information in public or unintended fields.", "A minor's data must be supplied by a parent, guardian or another person authorized by law."] },
      { title: "5. Data sources", items: ["Directly from you during registration, booking, account setup or support.", "From a business when it creates or manages a customer's booking and visit history.", "From Google or Facebook only when you choose social sign-in, limited to the identity data they provide.", "From your browser or device for security, session and system operation."] },
      { title: "6. Purposes and legal bases", items: ["Your consent and performance of a contract at your request: accounts, bookings, calendars, business tools, trials and selected plans. Where Armenian law provides, consent for data received under a contract and used only to perform it may be deemed given.", "A basis expressly provided by law: accounting and tax records, binding legal requests and mandatory retention.", "Security, fraud-prevention, error-diagnosis and service-protection data is processed only to the minimum extent necessary to perform the contract or meet a statutory security duty.", "Separate voluntary consent: marketing, social sign-in and other optional processing. These are not a condition of the core service.", "Consent continues for the stated purpose and retention period or until withdrawal. Withdrawal stops future optional processing but does not undo earlier lawful processing or mandatory retention. Withdrawing consent for necessary data may make account or booking support impossible."] },
      { title: "7. Data recipients", items: ["Hosting, backup, email and infrastructure providers, limited to what is necessary.", "Telegram only after a business enables alerts, and the map provider when the map is loaded.", "Google or Facebook only when social sign-in is selected.", "A bank or payment provider only for Vizit SaaS billing or a business's own direct payment connection. Customer service funds go directly to the business.", "Public authorities or others only for a binding legal request, rights protection or security need.", "We do not sell personal data."] },
      { title: "8. International transfers", paragraphs: ["Some technical providers may process data outside the Republic of Armenia. Transfers are limited to necessary data and rely on an applicable legal basis plus contractual and technical safeguards. You may request information about current providers from the privacy contact."] },
      { title: "9. Retention", items: ["Account and workspace data is kept while the account/business is active and afterward only as needed for closure, disputes, security and legal duties.", "Accounting and transaction records are retained for the period required by law.", "The relevant business generally determines retention of booking and professional data under its sector obligations.", "After a lawful closure or deletion request, data is deleted or anonymized when no retention basis remains. Backups expire through their secure rotation cycle."] },
      { title: "10. Security", items: ["Measures include HTTPS, role-based access, password hashing, request protection, rate limits and security logs.", "Staff and business access should be restricted to work-related need.", "No system can guarantee absolute security. Report suspected access or a possible breach promptly.", "A data incident will be investigated and notified as required by law."] },
      { title: "11. Your rights", items: ["Obtain information about processing and access your data.", "Correct inaccurate or incomplete data.", "Request blocking or destruction where no lawful basis remains, the purpose is complete, or data is outdated or unlawfully processed, subject to mandatory retention.", "Withdraw consent without affecting processing lawfully completed before withdrawal.", "Challenge a processor's action or inaction and seek the protection provided by law.", "Complain to the competent Armenian personal-data authority or a court."] },
      { title: "12. How to submit a request", paragraphs: [`Email ${LEGAL_ENTITY.email} with the account email/phone and your request. We may reasonably verify identity for security. We will respond within the period required by law. If a business controls the data, the request will be directed to it or completed on its lawful instructions.`] },
      { title: "13. Marketing, cookies and automated decisions", items: ["You may opt out of marketing through the message link or support. Service and security messages may continue.", "Cookies and browser storage are explained in the Cookie Policy.", "Vizit currently makes no solely automated decision with legal or similarly significant effects. An automated fraud or trial-abuse signal may trigger additional review."] },
      { title: "14. Changes and contact", paragraphs: [`A material update will carry a new version and, where required, renewed consent. Privacy questions: ${LEGAL_ENTITY.email}, ${LEGAL_ENTITY.phone}.`] },
    ],
  },
} as const;

export default function PrivacyPolicy() {
  const { locale } = useLanguage();
  const text = copy[locale];
  const sections = [
    {
      title: text.operatorTitle,
      content: (
        <>
          <p>{legalOperatorSummary(locale)}</p>
          <p>{text.operatorExtra}</p>
        </>
      ),
    },
    ...text.sections.map((section) => ({
      title: section.title,
      content: (
        <>
          {"paragraphs" in section ? section.paragraphs.map((paragraph) => <p key={paragraph}>{paragraph}</p>) : null}
          {"items" in section ? <ul className="list-disc space-y-1 pl-5">{section.items.map((item) => <li key={item}>{item}</li>)}</ul> : null}
        </>
      ),
    })),
  ];

  return <LegalPageTemplate title={text.title} description={text.description} updatedAt={LEGAL_DOCUMENT_VERSION} sections={sections} />;
}
