import LegalPageTemplate from "../components/marketing/LegalPageTemplate";
import { LEGAL_DOCUMENT_VERSION, LEGAL_ENTITY, legalOperatorSummary } from "../config/legal";
import { useLanguage } from "../contexts/LanguageContext";

const copy = {
  hy: {
    title: "Օգտագործման պայմաններ",
    description: "Vizit.am հարթակի, բիզնես հաշիվների, ամրագրումների և վճարովի SaaS պլանների պայմանները։",
    operatorTitle: "1. Օպերատոր և պայմանների ընդունում",
    operatorExtra: "Այս պայմանները և Գաղտնիության քաղաքականությունը հասանելի են մինչև գրանցումը կամ ամրագրումը։ Մինչև ուղարկելը կարող եք վերանայել և ուղղել ձևի տվյալները, իսկ ուղարկելուց հետո՝ փոփոխության համար դիմել աջակցությանը։ Համապատասխան դաշտը նշելով և գործողությունը հաստատելով՝ դուք էլեկտրոնային եղանակով ընդունում եք տվյալ պահին նշված տարբերակները․ համակարգը պահում է ընդունման ժամանակը, տարբերակները և անվտանգության տեխնիկական ապացույցը։ Կարող եք էջը պահպանել կամ տպել։ Անհատական գրավոր առաջարկը փոխարինում է այս պայմաններին միայն այն կետերով, որոնք այնտեղ հստակ նշված են։",
    sections: [
      { title: "2. Vizit-ի ծառայությունը և կողմերի դերերը", items: ["Vizit-ը օնլայն ամրագրման, հանրային էջերի, օրացույցի, թիմի, հաճախորդների և բիզնեսի կառավարման տեխնոլոգիական հարթակ է։", "Vizit-ը չի մատուցում բիզնեսի գովազդած գեղեցկության, բժշկական, կրթական, ավտո կամ այլ հիմնական ծառայությունը և այդ ծառայության պայմանագրի կողմ չէ։", "Հաճախորդի հիմնական ծառայության պայմանագիրը կնքվում է անմիջապես հաճախորդի և ընտրված բիզնեսի միջև։", "Vizit-ը բժշկական խորհրդատվություն կամ շտապ օգնություն չի տրամադրում։ Շտապ իրավիճակում դիմեք համապատասխան շտապ ծառայությանը։"] },
      { title: "3. Հաշիվներ, տարիք և անվտանգություն", items: ["Բիզնես հաշիվ կարող է բացել առնվազն 18 տարեկան, իրավունակ անձը, որն իրավունք ունի ներկայացնելու տվյալ բիզնեսը։", "Տրամադրեք ճշգրիտ և արդիական տվյալներ, պահպանեք մուտքի տվյալների գաղտնիությունը և անմիջապես տեղեկացրեք կասկածելի հասանելիության մասին։", "Բիզնեսի սեփականատերը պատասխանատու է իր կողմից ստեղծված աշխատակիցների դերերի, թույլտվությունների և գործողությունների համար։", "Հաճախորդի հաշիվը անձնական է։ Անչափահասի ամրագրումը կատարում է ծնողը, խնամակալը կամ օրենքով իրավասու այլ անձը։"] },
      { title: "4. Բիզնեսի պարտականությունները", items: ["Բիզնեսը պատասխանատու է իր անվան, հասցեների, լիցենզիաների կամ թույլտվությունների, ծառայությունների, գների, մասնագետների, աշխատանքային ժամերի և ազատ ժամանակների ճշգրտության համար։", "Բիզնեսը պարտավոր է հաճախորդին մինչև ամրագրումը հայտնել ծառայության էական պայմանները, վերջնական գինը, տևողությունը, չեղարկման կամ չներկայանալու կանոնները և անհրաժեշտ սահմանափակումները։", "Բժշկական կամ այլ կարգավորվող ծառայություն առաջարկող բիզնեսը ինքն է ապահովում մասնագիտական իրավասությունները, լիցենզիաները, տեղեկացված համաձայնությունը և ոլորտային գաղտնիությունը։", "Բիզնեսը հաճախորդների տվյալներն օգտագործում է միայն օրինական նպատակով և իր իրավասության սահմաններում։"] },
      { title: "5. Ամրագրումներ", items: ["Ամրագրումը ստեղծվում է ընտրված բիզնեսի հրապարակած ծառայության, մասնագետի և հասանելի ժամի հիման վրա։ Համակարգը գրանցում է այն պահանջվող հաստատման կոդը հասանելի կազմաձևված ալիքով ստուգելուց հետո։", "Առաջին հաստատման կոդը սովորաբար ուղարկվում է հաճախորդի նշած գործող էլ. հասցեին, երբ առաքումը տեխնիկապես հասանելի է։ Telegram-ը կարող է միացվել հաստատումից հետո, եթե տվյալ գործառույթը կազմաձևված է։", "Բիզնեսը պատասխանատու է այցի կատարման, ժամանակացույցի փոփոխության, չեղարկման և հաճախորդի հետ ծառայության վերաբերյալ հաղորդակցության համար։", "Համակարգային սխալի կամ ակնհայտ կրկնակի ամրագրման դեպքում կողմերը պետք է հնարավորինս արագ համաձայնեցնեն նոր ժամ կամ չեղարկում։"] },
      { title: "6. Փորձաշրջան և SaaS պլաններ", items: ["Իրավասու նոր բիզնեսին կարող է տրամադրվել մեկ 14-օրյա փորձաշրջան՝ առանց բանկային քարտի։ Կրկնակի կամ չարաշահող փորձաշրջանները կարող են մերժվել։", "Պլանի գինը, վճարման շրջանը, հիմնական գործառույթները և մասնագետների, ծառայությունների ու հասցեների սահմանաչափերը ցուցադրվում են գնային էջում կամ անհատական առաջարկում։ Անհատական գինը չի որոշվում բացառապես ավտոմատացված եղանակով․ այն կարող է հիմնվել բիզնեսի հայտնած կարիքների վրա և ամրագրվում է գրավոր առաջարկում։", "Մինչև վճարային պարտավորություն ստեղծող գործողությունը ցուցադրվում են վերջնական գումարը, արժույթը, շրջանը, կիրառելի հարկերը կամ վճարները, վճարման եղանակը և ավտոմատ երկարաձգման կարգավիճակը։ Եթե վճարման գործողությունը միջերեսում հասանելի չէ, վճարային պարտավորություն չի ստեղծվում։", "Հարթակն օգտագործելու համար պահանջվում է թարմացված աջակցվող բրաուզեր և ինտերնետ կապ։ Ակտիվ պլանի ընթացքում տրամադրվում են ծառայության աշխատանքի և անվտանգության համար անհրաժեշտ ծրագրային թարմացումները։ Որպես նախատեսվող կամ փորձնական նշված կապակցումը ներառված չի համարվում, քանի դեռ միջերեսում ակտիվ չէ։"] },
      { title: "7. Վճարումների մոդել", items: ["Vizit-ի եկամուտը բիզնեսների վճարած SaaS բաժանորդագրության վճարն է։", "Հաճախորդի կողմից բիզնեսի հիմնական ծառայության համար վճարումը կամ ավանդը կատարվում է անմիջապես տվյալ բիզնեսին՝ նրա սեփական բանկային կամ վճարային մատակարարի պայմանագրով։ Vizit-ը չի պահում այդ գումարները և դրանցից միջնորդավճար չի գանձում։", "Քանի դեռ կոնկրետ բիզնեսի պաշտոնական վճարային կապը հարթակում ակտիվ և հստակ ցուցադրված չէ, Vizit-ը չի ընդունում այդ բիզնեսի ծառայության առցանց վճարում կամ ավանդ։", "Վճարային մատակարարի առանձին պայմաններն ու գաղտնիության կանոնները կիրառվում են նրա էջում կատարվող գործարքի նկատմամբ։"] },
      { title: "8. Չեղարկումներ և վերադարձներ", items: ["Փորձաշրջանը կարող եք դադարեցնել ցանկացած պահին՝ առանց հետագա վճարման։", "SaaS պլանի չեղարկումը դադարեցնում է հաջորդ շրջանի երկարաձգումը։ Արդեն վճարված շրջանի հասանելիությունը սովորաբար պահպանվում է մինչև դրա ավարտը, եթե հաշիվը չի կասեցվել խախտման պատճառով։", "Կրկնակի, տեխնիկական սխալով կատարված կամ օրենքով վերադարձման ենթակա SaaS վճարման համար դիմեք աջակցությանը՝ նշելով հաշվի և գործարքի տվյալները։ Վերադարձը կատարվում է կիրառելի օրենքի և վճարման պահին ցուցադրված առաջարկի համաձայն։", "Հիմնական ծառայության վճարման, ավանդի, չեղարկման կամ վերադարձի հարցերը լուծվում են անմիջապես հաճախորդի և բիզնեսի միջև՝ տվյալ բիզնեսի նախապես ցուցադրված կանոններով։"] },
      { title: "9. Տվյալներ և գաղտնիություն", paragraphs: ["Անձնական տվյալների մշակումը նկարագրված է Գաղտնիության քաղաքականությունում։ Բիզնեսը իր հաճախորդների ծառայության և բժշկական տվյալների մասով ինքնուրույն տվյալների մշակող/վերահսկող է, իսկ Vizit-ը հարթակի տրամադրման համար գործում է նրա հանձնարարությամբ՝ բացառությամբ սեփական հաշվի, անվտանգության, աջակցության և իրավական պարտավորությունների տվյալների։"] },
      { title: "10. Ընդունելի օգտագործում", items: ["Արգելվում են չարտոնված մուտքը, սահմանափակումների շրջանցումը, վնասաբեր կոդը, ծառայության խափանումը կամ անվտանգության ստուգումն առանց գրավոր թույլտվության։", "Արգելվում են կեղծ կամ ապօրինի բովանդակությունը, խարդախությունը, սպամը, ուրիշի իրավունքների խախտումը և անձնական տվյալների ապօրինի հավաքումը։", "Չի թույլատրվում ստեղծել մոլորեցնող բիզնես էջեր կամ ներկայանալ որպես այն մասնագետը կամ կազմակերպությունը, որը չեք ներկայացնում։"] },
      { title: "11. Մտավոր սեփականություն", paragraphs: ["Vizit-ի ծրագրային կոդը, դիզայնը, ապրանքային նշանները և հարթակի սեփական բովանդակությունը պատկանում են օպերատորին կամ համապատասխան իրավատերերին։ Բիզնեսը պահպանում է իր բեռնած բովանդակության իրավունքները և Vizit-ին տալիս է միայն ծառայության աշխատանքի, ցուցադրման և տեխնիկական մշակման համար անհրաժեշտ ոչ բացառիկ թույլտվություն։"] },
      { title: "12. Հասանելիություն և փոփոխություններ", paragraphs: ["Մենք ձգտում ենք ապահովել կայուն աշխատանք, սակայն կարող են լինել սպասարկում, թարմացումներ, անվտանգության միջամտություններ կամ երրորդ կողմի խափանումներ։ Ակտիվ պլանի ընթացքում ծառայության համատեղելիության և անվտանգության համար անհրաժեշտ թարմացումները կարող են տեղադրվել ավտոմատ։ Էական պայմանների փոփոխության դեպքում հրապարակվում է նոր ամսաթիվ/տարբերակ, իսկ օրենքով կամ փոփոխության բնույթով պահանջվող դեպքում կպահանջվի նոր համաձայնություն։"] },
      { title: "13. Պատասխանատվության սահմաններ", paragraphs: ["Օրենքով թույլատրելի առավելագույն սահմաններում Vizit-ը պատասխանատու չէ բիզնեսի ծառայության որակի, մասնագիտական որոշումների, հաճախորդի կամ բիզնեսի տրամադրած սխալ տվյալների և կողմերի միջև վեճերի համար։ Այս դրույթը չի սահմանափակում այն պատասխանատվությունը, որը չի կարող բացառվել ՀՀ օրենսդրությամբ։"] },
      { title: "14. Կասեցում և հաշվի փակում", paragraphs: ["Հաշիվը կարող է ժամանակավորապես սահմանափակվել կամ փակվել էական խախտման, խարդախության, անվտանգության վտանգի, չվճարված գործող պլանի կամ պարտադիր իրավական պահանջի դեպքում։ Հաշվի փակման կամ տվյալների ջնջման դիմումը կարող եք ներկայացնել աջակցությանը․ օրենսդրությամբ պահպանման ենթակա տվյալները կարող են պահպանվել պահանջվող ժամկետով։"] },
      { title: "15. Կիրառելի իրավունք, բողոքներ և կապ", paragraphs: [`Կիրառվում է Հայաստանի Հանրապետության իրավունքը։ Գրավոր բողոքում նշեք հաշվի կոնտակտը, խնդրի փաստերը և ցանկալի լուծումը և ուղարկեք ${LEGAL_ENTITY.email} հասցեով։ Դիմումը կուսումնասիրվի, իսկ պատասխանը կուղարկվի կիրառելի օրենքով կամ վճարման պահին ցուցադրված առաջարկով սահմանված ժամկետում։ Չլուծվելու դեպքում կողմերը կարող են համաձայնությամբ օգտվել հաշտարարից կամ դիմել ՀՀ սպառողների պաշտպանության/այլ իրավասու մարմնին կամ դատարան։ Կապ՝ ${LEGAL_ENTITY.email}, ${LEGAL_ENTITY.phone}։ Հեռախոսազանգի համար կիրառվում է ձեր կապի օպերատորի սովորական սակագինը։`] },
    ],
  },
  ru: {
    title: "Условия использования",
    description: "Условия работы платформы Vizit.am, бизнес-аккаунтов, записей и платных SaaS-тарифов.",
    operatorTitle: "1. Оператор и принятие условий",
    operatorExtra: "Эти условия и Политика конфиденциальности доступны до регистрации или записи. До отправки формы можно проверить и исправить данные, а после отправки обратиться в поддержку для изменения. Отмечая соответствующее поле и подтверждая действие, вы принимаете указанные версии в электронной форме; система сохраняет время, версии и техническое доказательство принятия для безопасности. Страницу можно сохранить или распечатать. Индивидуальное письменное предложение заменяет эти условия только в прямо указанных в нём положениях.",
    sections: [
      { title: "2. Сервис Vizit и роли сторон", items: ["Vizit — технологическая платформа для онлайн-записи, публичных страниц, календаря, команды, клиентов и управления бизнесом.", "Vizit не оказывает рекламируемые бизнесом услуги красоты, медицины, образования, автосервиса или иные основные услуги и не является стороной договора об их оказании.", "Договор на основную услугу заключается непосредственно между клиентом и выбранным бизнесом.", "Vizit не оказывает медицинскую консультацию или экстренную помощь. В экстренной ситуации обратитесь в соответствующую службу."] },
      { title: "3. Аккаунты, возраст и безопасность", items: ["Бизнес-аккаунт может создать дееспособное лицо не моложе 18 лет, имеющее право представлять бизнес.", "Предоставляйте точные и актуальные данные, храните данные входа в тайне и немедленно сообщайте о подозрительном доступе.", "Владелец бизнеса отвечает за созданные им роли, разрешения и действия сотрудников.", "Аккаунт клиента является личным. Запись несовершеннолетнего выполняет родитель, опекун или иное уполномоченное законом лицо."] },
      { title: "4. Обязанности бизнеса", items: ["Бизнес отвечает за точность названия, адресов, лицензий или разрешений, услуг, цен, специалистов, рабочих часов и свободного времени.", "До записи бизнес должен сообщить клиенту существенные условия услуги, окончательную цену, длительность, правила отмены/неявки и необходимые ограничения.", "Медицинский или иной регулируемый бизнес самостоятельно обеспечивает профессиональные полномочия, лицензии, информированное согласие и отраслевую конфиденциальность.", "Бизнес использует данные клиентов только в законных целях и в пределах своих полномочий."] },
      { title: "5. Записи", items: ["Запись создаётся на основании опубликованных бизнесом услуги, специалиста и доступного времени. Система регистрирует её после проверки требуемого кода подтверждения через доступный настроенный канал.", "Первый код подтверждения обычно отправляется на действующий email клиента, когда доставка технически доступна. После подтверждения можно подключить Telegram, если эта функция настроена.", "Бизнес отвечает за оказание услуги, изменение расписания, отмену и общение с клиентом по основной услуге.", "При системной ошибке или очевидной двойной записи стороны должны как можно быстрее согласовать новое время или отмену."] },
      { title: "6. Пробный период и SaaS-тарифы", items: ["Подходящему новому бизнесу может быть предоставлен один 14-дневный пробный период без банковской карты. Повторные или злоупотребляющие попытки могут быть отклонены.", "Цена, платёжный период, основные функции и лимиты специалистов, услуг и адресов показываются на странице тарифов или в индивидуальном предложении. Индивидуальная цена не определяется исключительно автоматически: она может учитывать заявленные потребности бизнеса и фиксируется письменно.", "До действия, создающего обязанность оплаты, показываются итоговая сумма, валюта, период, применимые налоги/сборы, способ оплаты и статус автопродления. Если платёжное действие недоступно в интерфейсе, обязанность оплаты не возникает.", "Для работы нужен актуальный поддерживаемый браузер и интернет. В течение активного тарифа предоставляются необходимые для работы и безопасности программные обновления. Интеграция, обозначенная как планируемая или тестовая, не считается включённой, пока не активна в интерфейсе."] },
      { title: "7. Модель платежей", items: ["Доход Vizit формируется из SaaS-подписки, оплачиваемой бизнесами.", "Оплата или депозит клиента за основную услугу поступает напрямую бизнесу по его собственному договору с банком или платёжным провайдером. Vizit не хранит эти средства и не удерживает комиссию с них.", "Пока официальное платёжное подключение конкретного бизнеса не активно и не показано в интерфейсе, Vizit не принимает онлайн-оплату или депозит за его услуги.", "К операции на странице платёжного провайдера применяются его отдельные условия и правила конфиденциальности."] },
      { title: "8. Отмена и возвраты", items: ["Пробный период можно прекратить в любое время без последующей оплаты.", "Отмена SaaS-тарифа прекращает продление на следующий период. Доступ за уже оплаченный период обычно сохраняется до его окончания, если аккаунт не заблокирован из-за нарушения.", "При дублирующем, технически ошибочном или подлежащем возврату по закону платеже SaaS обратитесь в поддержку и укажите данные аккаунта и операции. Возврат выполняется по применимому праву и условиям, показанным при оплате.", "Оплата, депозит, отмена и возврат по основной услуге решаются непосредственно клиентом и бизнесом по заранее опубликованным правилам бизнеса."] },
      { title: "9. Данные и конфиденциальность", paragraphs: ["Обработка персональных данных описана в Политике конфиденциальности. В отношении сервисных и медицинских данных своих клиентов бизнес действует как самостоятельный контролёр/оператор данных, а Vizit обрабатывает их по поручению бизнеса для работы платформы, кроме данных, необходимых Vizit для аккаунтов, безопасности, поддержки и правовых обязанностей."] },
      { title: "10. Допустимое использование", items: ["Запрещены несанкционированный доступ, обход ограничений, вредоносный код, нарушение работы сервиса или проверка безопасности без письменного разрешения.", "Запрещены ложный или незаконный контент, мошенничество, спам, нарушение чужих прав и незаконный сбор персональных данных.", "Нельзя создавать вводящие в заблуждение страницы или выдавать себя за специалиста либо организацию, которых вы не представляете."] },
      { title: "11. Интеллектуальная собственность", paragraphs: ["Программный код, дизайн, обозначения и собственный контент Vizit принадлежат оператору или соответствующим правообладателям. Бизнес сохраняет права на загруженный контент и предоставляет Vizit только неисключительное разрешение, необходимое для работы, отображения и технической обработки сервиса."] },
      { title: "12. Доступность и изменения", paragraphs: ["Мы стремимся поддерживать стабильную работу, но возможны обслуживание, обновления, меры безопасности или сбои третьих сторон. В течение активного тарифа необходимые для совместимости и безопасности обновления могут устанавливаться автоматически. При существенном изменении публикуется новая дата/версия, а когда этого требует закон или характер изменения, запрашивается новое согласие."] },
      { title: "13. Ограничение ответственности", paragraphs: ["В максимально допустимых законом пределах Vizit не отвечает за качество услуг бизнеса, профессиональные решения, неверные данные клиента/бизнеса и споры между ними. Это не ограничивает ответственность, которую нельзя исключить по законодательству Республики Армения."] },
      { title: "14. Приостановка и закрытие аккаунта", paragraphs: ["Доступ может быть временно ограничен или прекращён при существенном нарушении, мошенничестве, угрозе безопасности, неоплаченном действующем тарифе или обязательном требовании закона. Запрос на закрытие аккаунта или удаление данных направляется в поддержку; данные, которые требуется хранить по закону, могут сохраняться установленный срок."] },
      { title: "15. Применимое право, жалобы и контакты", paragraphs: [`Применяется право Республики Армения. В письменной жалобе укажите контакт аккаунта, обстоятельства и желаемое решение и отправьте её на ${LEGAL_ENTITY.email}. Обращение будет рассмотрено, а ответ направлен в срок, установленный применимым законом или предложением, показанным при оплате. Если спор не урегулирован, стороны могут по соглашению обратиться к медиатору либо в компетентный орган по защите потребителей, иной орган или суд Республики Армения. Контакты: ${LEGAL_ENTITY.email}, ${LEGAL_ENTITY.phone}. Звонок оплачивается по обычному тарифу вашего оператора связи.`] },
    ],
  },
  en: {
    title: "Terms of use",
    description: "Terms governing the Vizit.am platform, business accounts, bookings and paid SaaS plans.",
    operatorTitle: "1. Operator and acceptance",
    operatorExtra: "These terms and the Privacy Policy are available before registration or booking. You can review and correct form data before submission and contact support for changes afterward. By checking the relevant box and confirming the action, you electronically accept the versions identified at that time; the system records the time, versions and technical acceptance evidence for security. You may save or print this page. A written custom offer overrides these terms only where it expressly says so.",
    sections: [
      { title: "2. The Vizit service and the parties", items: ["Vizit is a technology platform for online booking, public pages, calendars, staff, clients and business management.", "Vizit does not provide the beauty, healthcare, education, automotive or other underlying service advertised by a business and is not a party to that service contract.", "The underlying service contract is made directly between the customer and the selected business.", "Vizit does not provide medical advice or emergency assistance. Contact the appropriate emergency service in an emergency."] },
      { title: "3. Accounts, age and security", items: ["A business account may be created by a legally capable person aged 18 or over who is authorized to represent the business.", "Provide accurate, current information, keep credentials confidential and promptly report suspected unauthorized access.", "The business owner is responsible for staff roles, permissions and activity created under the business account.", "A client account is personal. A booking for a minor must be made by a parent, guardian or another person authorized by law."] },
      { title: "4. Business responsibilities", items: ["The business is responsible for the accuracy of its name, locations, licences or permits, services, prices, staff, working hours and availability.", "Before booking, the business must disclose the material service terms, final price, duration, cancellation/no-show policy and relevant restrictions.", "A healthcare or other regulated business is solely responsible for professional authorization, licences, informed consent and sector-specific confidentiality.", "The business may use customer data only for lawful purposes and within its authority."] },
      { title: "5. Bookings", items: ["A booking is created from the service, specialist and available time published by the business. The system records it after the required confirmation code is verified through an available configured channel.", "The first confirmation code is normally sent to the customer's valid email address when delivery is technically available. Telegram may be connected after verification if that feature is configured.", "The business is responsible for service delivery, schedule changes, cancellations and service-related communication with the customer.", "If a system error or obvious double booking occurs, the parties should promptly agree a new time or cancellation."] },
      { title: "6. Trial and SaaS plans", items: ["An eligible new business may receive one 14-day trial without a bank card. Duplicate or abusive trial attempts may be refused.", "The price, billing period, core functionality and staff, service and location limits are shown on the pricing page or in a custom offer. Custom pricing is not decided solely by automated processing: it may reflect needs stated by the business and is recorded in writing.", "Before any action creating a payment obligation, the final amount, currency, period, applicable taxes/fees, payment method and auto-renewal status will be shown. If the payment action is unavailable in the interface, no payment obligation arises.", "A current supported browser and internet connection are required. Software updates needed for operation and security are provided during an active plan. An integration described as planned or experimental is not included until it is active in the interface."] },
      { title: "7. Payment model", items: ["Vizit earns revenue from SaaS subscription fees paid by businesses.", "A customer's payment or deposit for the underlying service is paid directly to that business under its own agreement with a bank or payment provider. Vizit does not hold those funds or charge a commission on them.", "Until a specific business's official payment connection is active and clearly displayed, Vizit does not accept online payments or deposits for that business's services.", "The payment provider's separate terms and privacy rules apply to a transaction completed on its page."] },
      { title: "8. Cancellation and refunds", items: ["A trial may be stopped at any time without a later charge.", "Cancelling a SaaS plan stops renewal for the next period. Access for an already paid period normally continues until its end unless the account is suspended for breach.", "For a duplicate, technically erroneous or legally refundable SaaS charge, contact support with the account and transaction details. Refunds follow applicable law and the offer shown at payment.", "Payment, deposit, cancellation and refund issues for the underlying service are resolved directly between the customer and the business under the business's policy disclosed before booking."] },
      { title: "9. Data and privacy", paragraphs: ["Personal-data processing is described in the Privacy Policy. For its customers' service and medical data, the business acts as the independent controller, while Vizit processes that data on the business's instructions to provide the platform, except for data Vizit needs for its own accounts, security, support and legal obligations."] },
      { title: "10. Acceptable use", items: ["Do not attempt unauthorized access, bypass restrictions, distribute malicious code, disrupt the service or test security without written permission.", "Do not publish false or unlawful content, commit fraud, send spam, infringe another person's rights or unlawfully collect personal data.", "Do not create misleading business pages or impersonate a professional or organization you do not represent."] },
      { title: "11. Intellectual property", paragraphs: ["Vizit's software, design, marks and proprietary content belong to the operator or relevant rights holders. A business retains rights in its uploaded content and grants Vizit only the non-exclusive permission needed to operate, display and technically process the service."] },
      { title: "12. Availability and changes", paragraphs: ["We aim to keep the service stable, but maintenance, updates, security work or third-party outages may occur. Updates necessary for compatibility and security may be installed automatically during an active plan. A material change will carry a new date/version, and renewed acceptance will be requested where required by law or the nature of the change."] },
      { title: "13. Liability limits", paragraphs: ["To the maximum extent allowed by law, Vizit is not responsible for the quality of a business's service, professional decisions, incorrect customer/business data or disputes between them. Nothing here limits liability that cannot be excluded under Armenian law."] },
      { title: "14. Suspension and account closure", paragraphs: ["Access may be restricted or terminated for a material breach, fraud, security risk, an unpaid active plan or a binding legal requirement. Account closure or data deletion requests may be sent to support; records that must be kept by law may be retained for the required period."] },
      { title: "15. Governing law, complaints and contact", paragraphs: [`The laws of the Republic of Armenia apply. A written complaint should identify the account contact, facts and requested resolution and be sent to ${LEGAL_ENTITY.email}. It will be reviewed and answered within the period set by applicable law or the offer displayed at payment. If unresolved, the parties may agree to mediation or apply to the competent Armenian consumer-protection or other authority or a court. Contact: ${LEGAL_ENTITY.email}, ${LEGAL_ENTITY.phone}. Calls are charged at your carrier's ordinary rate.`] },
    ],
  },
} as const;

export default function Terms() {
  const { locale } = useLanguage();
  const text = copy[locale];
  const sections = [
    {
      title: text.operatorTitle,
      content: (
        <>
          <p>{legalOperatorSummary(locale)}</p>
          <p>{text.operatorExtra}</p>
        </>
      ),
    },
    ...text.sections.map((section) => ({
      title: section.title,
      content: (
        <>
          {"paragraphs" in section ? section.paragraphs.map((paragraph) => <p key={paragraph}>{paragraph}</p>) : null}
          {"items" in section ? <ul className="list-disc space-y-1 pl-5">{section.items.map((item) => <li key={item}>{item}</li>)}</ul> : null}
        </>
      ),
    })),
  ];

  return <LegalPageTemplate title={text.title} description={text.description} updatedAt={LEGAL_DOCUMENT_VERSION} sections={sections} />;
}
